# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
#   'bundle exec jekyll serve'.
# If you change this file, please restart the server process.

# -------------------------------------
# Site Settings
# -------------------------------------
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title  }}, {{ site.email  }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable  }}.

name: ???
title: GSOC Devlog
description: Tracking progress on the Mozilla Study Group Viz Project

gh_name: mozillascience
gh_commits: https://www.github.com/mozillascience/studyGroup-GSOC/commits/?author=AnamikaD
gh_prs: https://github.com/mozillascience/studyGroup-GSOC/pulls?utf8=%E2%9C%93&q=is:pr+author:AnamikaD
gh_issues: https://github.com/mozillascience/studyGroup-GSOC/issues?utf8=%E2%9C%93&q=is:issue+author:AnamikaD
gh_project: https://www.github.com/mozillascience/studyGroup-GSOC


# -------------------------------------
# Build Settings
# -------------------------------------
markdown: kramdown
future: true
encoding: utf-8
highlighter: rouge
